package com.lrexperts.liferay.liferayofthings.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SensorValue service. Represents a row in the &quot;LRoT_SensorValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.lrexperts.liferay.liferayofthings.model.impl.SensorValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.lrexperts.liferay.liferayofthings.model.impl.SensorValueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SensorValue
 * @see com.lrexperts.liferay.liferayofthings.model.impl.SensorValueImpl
 * @see com.lrexperts.liferay.liferayofthings.model.impl.SensorValueModelImpl
 * @generated
 */
public interface SensorValueModel extends BaseModel<SensorValue> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a sensor value model instance should use the {@link SensorValue} interface instead.
     */

    /**
     * Returns the primary key of this sensor value.
     *
     * @return the primary key of this sensor value
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this sensor value.
     *
     * @param primaryKey the primary key of this sensor value
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this sensor value.
     *
     * @return the uuid of this sensor value
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this sensor value.
     *
     * @param uuid the uuid of this sensor value
     */
    public void setUuid(String uuid);

    /**
     * Returns the sensor value ID of this sensor value.
     *
     * @return the sensor value ID of this sensor value
     */
    public long getSensorValueId();

    /**
     * Sets the sensor value ID of this sensor value.
     *
     * @param sensorValueId the sensor value ID of this sensor value
     */
    public void setSensorValueId(long sensorValueId);

    /**
     * Returns the company ID of this sensor value.
     *
     * @return the company ID of this sensor value
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this sensor value.
     *
     * @param companyId the company ID of this sensor value
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this sensor value.
     *
     * @return the group ID of this sensor value
     */
    public long getGroupId();

    /**
     * Sets the group ID of this sensor value.
     *
     * @param groupId the group ID of this sensor value
     */
    public void setGroupId(long groupId);

    /**
     * Returns the sensor ID of this sensor value.
     *
     * @return the sensor ID of this sensor value
     */
    public long getSensorId();

    /**
     * Sets the sensor ID of this sensor value.
     *
     * @param sensorId the sensor ID of this sensor value
     */
    public void setSensorId(long sensorId);

    /**
     * Returns the value of this sensor value.
     *
     * @return the value of this sensor value
     */
    @AutoEscape
    public String getValue();

    /**
     * Sets the value of this sensor value.
     *
     * @param value the value of this sensor value
     */
    public void setValue(String value);

    /**
     * Returns the create date of this sensor value.
     *
     * @return the create date of this sensor value
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this sensor value.
     *
     * @param createDate the create date of this sensor value
     */
    public void setCreateDate(Date createDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.lrexperts.liferay.liferayofthings.model.SensorValue sensorValue);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.lrexperts.liferay.liferayofthings.model.SensorValue> toCacheModel();

    @Override
    public com.lrexperts.liferay.liferayofthings.model.SensorValue toEscapedModel();

    @Override
    public com.lrexperts.liferay.liferayofthings.model.SensorValue toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
