package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.Actuator;
import com.lrexperts.liferay.liferayofthings.service.ActuatorLocalServiceUtil;

/**
 * The extended model base implementation for the Actuator service. Represents a row in the &quot;LRoT_Actuator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActuatorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActuatorImpl
 * @see com.lrexperts.liferay.liferayofthings.model.Actuator
 * @generated
 */
public abstract class ActuatorBaseImpl extends ActuatorModelImpl
    implements Actuator {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a actuator model instance should use the {@link Actuator} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ActuatorLocalServiceUtil.addActuator(this);
        } else {
            ActuatorLocalServiceUtil.updateActuator(this);
        }
    }
}
