package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.ActuatorType;
import com.lrexperts.liferay.liferayofthings.service.ActuatorTypeLocalServiceUtil;

/**
 * The extended model base implementation for the ActuatorType service. Represents a row in the &quot;LRoT_ActuatorType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActuatorTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ActuatorTypeImpl
 * @see com.lrexperts.liferay.liferayofthings.model.ActuatorType
 * @generated
 */
public abstract class ActuatorTypeBaseImpl extends ActuatorTypeModelImpl
    implements ActuatorType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a actuator type model instance should use the {@link ActuatorType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ActuatorTypeLocalServiceUtil.addActuatorType(this);
        } else {
            ActuatorTypeLocalServiceUtil.updateActuatorType(this);
        }
    }
}
