package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.SensorValue;
import com.lrexperts.liferay.liferayofthings.service.SensorValueLocalServiceUtil;

/**
 * The extended model base implementation for the SensorValue service. Represents a row in the &quot;LRoT_SensorValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SensorValueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SensorValueImpl
 * @see com.lrexperts.liferay.liferayofthings.model.SensorValue
 * @generated
 */
public abstract class SensorValueBaseImpl extends SensorValueModelImpl
    implements SensorValue {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sensor value model instance should use the {@link SensorValue} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SensorValueLocalServiceUtil.addSensorValue(this);
        } else {
            SensorValueLocalServiceUtil.updateSensorValue(this);
        }
    }
}
