package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.Sensor;
import com.lrexperts.liferay.liferayofthings.service.SensorLocalServiceUtil;

/**
 * The extended model base implementation for the Sensor service. Represents a row in the &quot;LRoT_Sensor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SensorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SensorImpl
 * @see com.lrexperts.liferay.liferayofthings.model.Sensor
 * @generated
 */
public abstract class SensorBaseImpl extends SensorModelImpl implements Sensor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sensor model instance should use the {@link Sensor} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SensorLocalServiceUtil.addSensor(this);
        } else {
            SensorLocalServiceUtil.updateSensor(this);
        }
    }
}
