package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.lrexperts.liferay.liferayofthings.model.Sensor;
import com.lrexperts.liferay.liferayofthings.model.SensorModel;
import com.lrexperts.liferay.liferayofthings.model.SensorSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the Sensor service. Represents a row in the &quot;LRoT_Sensor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.lrexperts.liferay.liferayofthings.model.SensorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SensorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SensorImpl
 * @see com.lrexperts.liferay.liferayofthings.model.Sensor
 * @see com.lrexperts.liferay.liferayofthings.model.SensorModel
 * @generated
 */
@JSON(strict = true)
public class SensorModelImpl extends BaseModelImpl<Sensor>
    implements SensorModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sensor model instance should use the {@link com.lrexperts.liferay.liferayofthings.model.Sensor} interface instead.
     */
    public static final String TABLE_NAME = "LRoT_Sensor";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "sensorId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "thingId", Types.BIGINT },
            { "sensorTypeId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "endpoint", Types.VARCHAR },
            { "enabled", Types.BOOLEAN },
            { "status", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table LRoT_Sensor (uuid_ VARCHAR(75) null,sensorId LONG not null primary key,companyId LONG,groupId LONG,thingId LONG,sensorTypeId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name STRING null,description STRING null,endpoint VARCHAR(255) null,enabled BOOLEAN,status INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table LRoT_Sensor";
    public static final String ORDER_BY_JPQL = " ORDER BY sensor.name ASC";
    public static final String ORDER_BY_SQL = " ORDER BY LRoT_Sensor.name ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.lrexperts.liferay.liferayofthings.model.Sensor"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.lrexperts.liferay.liferayofthings.model.Sensor"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.lrexperts.liferay.liferayofthings.model.Sensor"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long ENABLED_COLUMN_BITMASK = 2L;
    public static long ENDPOINT_COLUMN_BITMASK = 4L;
    public static long GROUPID_COLUMN_BITMASK = 8L;
    public static long SENSORTYPEID_COLUMN_BITMASK = 16L;
    public static long STATUS_COLUMN_BITMASK = 32L;
    public static long THINGID_COLUMN_BITMASK = 64L;
    public static long UUID_COLUMN_BITMASK = 128L;
    public static long NAME_COLUMN_BITMASK = 256L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.lrexperts.liferay.liferayofthings.model.Sensor"));
    private static ClassLoader _classLoader = Sensor.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Sensor.class };
    private String _uuid;
    private String _originalUuid;
    private long _sensorId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _thingId;
    private long _originalThingId;
    private boolean _setOriginalThingId;
    private long _sensorTypeId;
    private long _originalSensorTypeId;
    private boolean _setOriginalSensorTypeId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _nameCurrentLanguageId;
    private String _description;
    private String _descriptionCurrentLanguageId;
    private String _endpoint;
    private String _originalEndpoint;
    private boolean _enabled;
    private boolean _originalEnabled;
    private boolean _setOriginalEnabled;
    private int _status;
    private int _originalStatus;
    private boolean _setOriginalStatus;
    private long _columnBitmask;
    private Sensor _escapedModel;

    public SensorModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Sensor toModel(SensorSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Sensor model = new SensorImpl();

        model.setUuid(soapModel.getUuid());
        model.setSensorId(soapModel.getSensorId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setGroupId(soapModel.getGroupId());
        model.setThingId(soapModel.getThingId());
        model.setSensorTypeId(soapModel.getSensorTypeId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setDescription(soapModel.getDescription());
        model.setEndpoint(soapModel.getEndpoint());
        model.setEnabled(soapModel.getEnabled());
        model.setStatus(soapModel.getStatus());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Sensor> toModels(SensorSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Sensor> models = new ArrayList<Sensor>(soapModels.length);

        for (SensorSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _sensorId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setSensorId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _sensorId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Sensor.class;
    }

    @Override
    public String getModelClassName() {
        return Sensor.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("sensorId", getSensorId());
        attributes.put("companyId", getCompanyId());
        attributes.put("groupId", getGroupId());
        attributes.put("thingId", getThingId());
        attributes.put("sensorTypeId", getSensorTypeId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("description", getDescription());
        attributes.put("endpoint", getEndpoint());
        attributes.put("enabled", getEnabled());
        attributes.put("status", getStatus());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long sensorId = (Long) attributes.get("sensorId");

        if (sensorId != null) {
            setSensorId(sensorId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long thingId = (Long) attributes.get("thingId");

        if (thingId != null) {
            setThingId(thingId);
        }

        Long sensorTypeId = (Long) attributes.get("sensorTypeId");

        if (sensorTypeId != null) {
            setSensorTypeId(sensorTypeId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String description = (String) attributes.get("description");

        if (description != null) {
            setDescription(description);
        }

        String endpoint = (String) attributes.get("endpoint");

        if (endpoint != null) {
            setEndpoint(endpoint);
        }

        Boolean enabled = (Boolean) attributes.get("enabled");

        if (enabled != null) {
            setEnabled(enabled);
        }

        Integer status = (Integer) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getSensorId() {
        return _sensorId;
    }

    @Override
    public void setSensorId(long sensorId) {
        _sensorId = sensorId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getThingId() {
        return _thingId;
    }

    @Override
    public void setThingId(long thingId) {
        _columnBitmask |= THINGID_COLUMN_BITMASK;

        if (!_setOriginalThingId) {
            _setOriginalThingId = true;

            _originalThingId = _thingId;
        }

        _thingId = thingId;
    }

    public long getOriginalThingId() {
        return _originalThingId;
    }

    @JSON
    @Override
    public long getSensorTypeId() {
        return _sensorTypeId;
    }

    @Override
    public void setSensorTypeId(long sensorTypeId) {
        _columnBitmask |= SENSORTYPEID_COLUMN_BITMASK;

        if (!_setOriginalSensorTypeId) {
            _setOriginalSensorTypeId = true;

            _originalSensorTypeId = _sensorTypeId;
        }

        _sensorTypeId = sensorTypeId;
    }

    public long getOriginalSensorTypeId() {
        return _originalSensorTypeId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public String getName(Locale locale) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getName(languageId);
    }

    @Override
    public String getName(Locale locale, boolean useDefault) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getName(languageId, useDefault);
    }

    @Override
    public String getName(String languageId) {
        return LocalizationUtil.getLocalization(getName(), languageId);
    }

    @Override
    public String getName(String languageId, boolean useDefault) {
        return LocalizationUtil.getLocalization(getName(), languageId,
            useDefault);
    }

    @Override
    public String getNameCurrentLanguageId() {
        return _nameCurrentLanguageId;
    }

    @JSON
    @Override
    public String getNameCurrentValue() {
        Locale locale = getLocale(_nameCurrentLanguageId);

        return getName(locale);
    }

    @Override
    public Map<Locale, String> getNameMap() {
        return LocalizationUtil.getLocalizationMap(getName());
    }

    @Override
    public void setName(String name) {
        _columnBitmask = -1L;

        _name = name;
    }

    @Override
    public void setName(String name, Locale locale) {
        setName(name, locale, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setName(String name, Locale locale, Locale defaultLocale) {
        String languageId = LocaleUtil.toLanguageId(locale);
        String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

        if (Validator.isNotNull(name)) {
            setName(LocalizationUtil.updateLocalization(getName(), "Name",
                    name, languageId, defaultLanguageId));
        } else {
            setName(LocalizationUtil.removeLocalization(getName(), "Name",
                    languageId));
        }
    }

    @Override
    public void setNameCurrentLanguageId(String languageId) {
        _nameCurrentLanguageId = languageId;
    }

    @Override
    public void setNameMap(Map<Locale, String> nameMap) {
        setNameMap(nameMap, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
        if (nameMap == null) {
            return;
        }

        setName(LocalizationUtil.updateLocalization(nameMap, getName(), "Name",
                LocaleUtil.toLanguageId(defaultLocale)));
    }

    @JSON
    @Override
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    @Override
    public String getDescription(Locale locale) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getDescription(languageId);
    }

    @Override
    public String getDescription(Locale locale, boolean useDefault) {
        String languageId = LocaleUtil.toLanguageId(locale);

        return getDescription(languageId, useDefault);
    }

    @Override
    public String getDescription(String languageId) {
        return LocalizationUtil.getLocalization(getDescription(), languageId);
    }

    @Override
    public String getDescription(String languageId, boolean useDefault) {
        return LocalizationUtil.getLocalization(getDescription(), languageId,
            useDefault);
    }

    @Override
    public String getDescriptionCurrentLanguageId() {
        return _descriptionCurrentLanguageId;
    }

    @JSON
    @Override
    public String getDescriptionCurrentValue() {
        Locale locale = getLocale(_descriptionCurrentLanguageId);

        return getDescription(locale);
    }

    @Override
    public Map<Locale, String> getDescriptionMap() {
        return LocalizationUtil.getLocalizationMap(getDescription());
    }

    @Override
    public void setDescription(String description) {
        _description = description;
    }

    @Override
    public void setDescription(String description, Locale locale) {
        setDescription(description, locale, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setDescription(String description, Locale locale,
        Locale defaultLocale) {
        String languageId = LocaleUtil.toLanguageId(locale);
        String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

        if (Validator.isNotNull(description)) {
            setDescription(LocalizationUtil.updateLocalization(
                    getDescription(), "Description", description, languageId,
                    defaultLanguageId));
        } else {
            setDescription(LocalizationUtil.removeLocalization(
                    getDescription(), "Description", languageId));
        }
    }

    @Override
    public void setDescriptionCurrentLanguageId(String languageId) {
        _descriptionCurrentLanguageId = languageId;
    }

    @Override
    public void setDescriptionMap(Map<Locale, String> descriptionMap) {
        setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
    }

    @Override
    public void setDescriptionMap(Map<Locale, String> descriptionMap,
        Locale defaultLocale) {
        if (descriptionMap == null) {
            return;
        }

        setDescription(LocalizationUtil.updateLocalization(descriptionMap,
                getDescription(), "Description",
                LocaleUtil.toLanguageId(defaultLocale)));
    }

    @JSON
    @Override
    public String getEndpoint() {
        if (_endpoint == null) {
            return StringPool.BLANK;
        } else {
            return _endpoint;
        }
    }

    @Override
    public void setEndpoint(String endpoint) {
        _columnBitmask |= ENDPOINT_COLUMN_BITMASK;

        if (_originalEndpoint == null) {
            _originalEndpoint = _endpoint;
        }

        _endpoint = endpoint;
    }

    public String getOriginalEndpoint() {
        return GetterUtil.getString(_originalEndpoint);
    }

    @JSON
    @Override
    public boolean getEnabled() {
        return _enabled;
    }

    @Override
    public boolean isEnabled() {
        return _enabled;
    }

    @Override
    public void setEnabled(boolean enabled) {
        _columnBitmask |= ENABLED_COLUMN_BITMASK;

        if (!_setOriginalEnabled) {
            _setOriginalEnabled = true;

            _originalEnabled = _enabled;
        }

        _enabled = enabled;
    }

    public boolean getOriginalEnabled() {
        return _originalEnabled;
    }

    @JSON
    @Override
    public int getStatus() {
        return _status;
    }

    @Override
    public void setStatus(int status) {
        _columnBitmask |= STATUS_COLUMN_BITMASK;

        if (!_setOriginalStatus) {
            _setOriginalStatus = true;

            _originalStatus = _status;
        }

        _status = status;
    }

    public int getOriginalStatus() {
        return _originalStatus;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Sensor.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Sensor.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public String[] getAvailableLanguageIds() {
        Set<String> availableLanguageIds = new TreeSet<String>();

        Map<Locale, String> nameMap = getNameMap();

        for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
            Locale locale = entry.getKey();
            String value = entry.getValue();

            if (Validator.isNotNull(value)) {
                availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
            }
        }

        Map<Locale, String> descriptionMap = getDescriptionMap();

        for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
            Locale locale = entry.getKey();
            String value = entry.getValue();

            if (Validator.isNotNull(value)) {
                availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
            }
        }

        return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
    }

    @Override
    public String getDefaultLanguageId() {
        String xml = getName();

        if (xml == null) {
            return StringPool.BLANK;
        }

        Locale defaultLocale = LocaleUtil.getSiteDefault();

        return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
    }

    @Override
    public void prepareLocalizedFieldsForImport() throws LocaleException {
        prepareLocalizedFieldsForImport(null);
    }

    @Override
    @SuppressWarnings("unused")
    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException {
        Locale defaultLocale = LocaleUtil.getSiteDefault();

        String modelDefaultLanguageId = getDefaultLanguageId();

        String name = getName(defaultLocale);

        if (Validator.isNull(name)) {
            setName(getName(modelDefaultLanguageId), defaultLocale);
        } else {
            setName(getName(defaultLocale), defaultLocale, defaultLocale);
        }

        String description = getDescription(defaultLocale);

        if (Validator.isNull(description)) {
            setDescription(getDescription(modelDefaultLanguageId), defaultLocale);
        } else {
            setDescription(getDescription(defaultLocale), defaultLocale,
                defaultLocale);
        }
    }

    @Override
    public Sensor toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Sensor) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        SensorImpl sensorImpl = new SensorImpl();

        sensorImpl.setUuid(getUuid());
        sensorImpl.setSensorId(getSensorId());
        sensorImpl.setCompanyId(getCompanyId());
        sensorImpl.setGroupId(getGroupId());
        sensorImpl.setThingId(getThingId());
        sensorImpl.setSensorTypeId(getSensorTypeId());
        sensorImpl.setUserId(getUserId());
        sensorImpl.setUserName(getUserName());
        sensorImpl.setCreateDate(getCreateDate());
        sensorImpl.setModifiedDate(getModifiedDate());
        sensorImpl.setName(getName());
        sensorImpl.setDescription(getDescription());
        sensorImpl.setEndpoint(getEndpoint());
        sensorImpl.setEnabled(getEnabled());
        sensorImpl.setStatus(getStatus());

        sensorImpl.resetOriginalValues();

        return sensorImpl;
    }

    @Override
    public int compareTo(Sensor sensor) {
        int value = 0;

        value = getName().compareTo(sensor.getName());

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Sensor)) {
            return false;
        }

        Sensor sensor = (Sensor) obj;

        long primaryKey = sensor.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        SensorModelImpl sensorModelImpl = this;

        sensorModelImpl._originalUuid = sensorModelImpl._uuid;

        sensorModelImpl._originalCompanyId = sensorModelImpl._companyId;

        sensorModelImpl._setOriginalCompanyId = false;

        sensorModelImpl._originalGroupId = sensorModelImpl._groupId;

        sensorModelImpl._setOriginalGroupId = false;

        sensorModelImpl._originalThingId = sensorModelImpl._thingId;

        sensorModelImpl._setOriginalThingId = false;

        sensorModelImpl._originalSensorTypeId = sensorModelImpl._sensorTypeId;

        sensorModelImpl._setOriginalSensorTypeId = false;

        sensorModelImpl._originalEndpoint = sensorModelImpl._endpoint;

        sensorModelImpl._originalEnabled = sensorModelImpl._enabled;

        sensorModelImpl._setOriginalEnabled = false;

        sensorModelImpl._originalStatus = sensorModelImpl._status;

        sensorModelImpl._setOriginalStatus = false;

        sensorModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Sensor> toCacheModel() {
        SensorCacheModel sensorCacheModel = new SensorCacheModel();

        sensorCacheModel.uuid = getUuid();

        String uuid = sensorCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            sensorCacheModel.uuid = null;
        }

        sensorCacheModel.sensorId = getSensorId();

        sensorCacheModel.companyId = getCompanyId();

        sensorCacheModel.groupId = getGroupId();

        sensorCacheModel.thingId = getThingId();

        sensorCacheModel.sensorTypeId = getSensorTypeId();

        sensorCacheModel.userId = getUserId();

        sensorCacheModel.userName = getUserName();

        String userName = sensorCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            sensorCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            sensorCacheModel.createDate = createDate.getTime();
        } else {
            sensorCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            sensorCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            sensorCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        sensorCacheModel.name = getName();

        String name = sensorCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            sensorCacheModel.name = null;
        }

        sensorCacheModel.description = getDescription();

        String description = sensorCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            sensorCacheModel.description = null;
        }

        sensorCacheModel.endpoint = getEndpoint();

        String endpoint = sensorCacheModel.endpoint;

        if ((endpoint != null) && (endpoint.length() == 0)) {
            sensorCacheModel.endpoint = null;
        }

        sensorCacheModel.enabled = getEnabled();

        sensorCacheModel.status = getStatus();

        return sensorCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(31);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", sensorId=");
        sb.append(getSensorId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", thingId=");
        sb.append(getThingId());
        sb.append(", sensorTypeId=");
        sb.append(getSensorTypeId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", endpoint=");
        sb.append(getEndpoint());
        sb.append(", enabled=");
        sb.append(getEnabled());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(49);

        sb.append("<model><model-name>");
        sb.append("com.lrexperts.liferay.liferayofthings.model.Sensor");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sensorId</column-name><column-value><![CDATA[");
        sb.append(getSensorId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>thingId</column-name><column-value><![CDATA[");
        sb.append(getThingId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sensorTypeId</column-name><column-value><![CDATA[");
        sb.append(getSensorTypeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>endpoint</column-name><column-value><![CDATA[");
        sb.append(getEndpoint());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>enabled</column-name><column-value><![CDATA[");
        sb.append(getEnabled());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
