package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.Thing;
import com.lrexperts.liferay.liferayofthings.service.ThingLocalServiceUtil;

/**
 * The extended model base implementation for the Thing service. Represents a row in the &quot;LRoT_Thing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ThingImpl
 * @see com.lrexperts.liferay.liferayofthings.model.Thing
 * @generated
 */
public abstract class ThingBaseImpl extends ThingModelImpl implements Thing {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a thing model instance should use the {@link Thing} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ThingLocalServiceUtil.addThing(this);
        } else {
            ThingLocalServiceUtil.updateThing(this);
        }
    }
}
