package com.lrexperts.liferay.liferayofthings.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrexperts.liferay.liferayofthings.model.ThingGroup;
import com.lrexperts.liferay.liferayofthings.service.ThingGroupLocalServiceUtil;

/**
 * The extended model base implementation for the ThingGroup service. Represents a row in the &quot;LRoT_ThingGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThingGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ThingGroupImpl
 * @see com.lrexperts.liferay.liferayofthings.model.ThingGroup
 * @generated
 */
public abstract class ThingGroupBaseImpl extends ThingGroupModelImpl
    implements ThingGroup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a thing group model instance should use the {@link ThingGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ThingGroupLocalServiceUtil.addThingGroup(this);
        } else {
            ThingGroupLocalServiceUtil.updateThingGroup(this);
        }
    }
}
